#### get reservations
#GET http://localhost:4000/reservations
#content-type: application/json
##Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBZG1pbiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxNTUzNzgwNn0.Nwt2BcJDQDJ1M1qIFVzg00BSdJrQFelzxgPaIYYFwtk
#




